### PR TITLE
appveyor + x64

### PR DESCRIPTION
**Pull request by chcg**
- initial appveyor.yml CI config
- added x64 config
- updated dllexport

, see https://ci.appveyor.com/project/chcg/scripts-npp/build/1.0.4.3

- debug build still fails as project UnitTest\UnitTest.csproj is not part of the repo

### CODE REVIEW

**Comment by chcg** [comment]
@oleg-shilo 
- What about the unittest issue?
- Do you think it is possible to do the publishing process on appveyor? Seems at least some data is missing like e.g. the samples. The link from the readme.txt  www.csscript.net/npp/nppscript.html is not valid.

**Comment by oleg-shilo** [comment]
Yes utests will need to be updates. And all other issues fixed.
All this project will need to be revisited and updated. Just after CS-Script.Npp is released.

Though I am not sold on publishing via appveyor. There are a few points I feel uneasy about:
- It builds on every commit. It's great, but it contradicts with the common publishing practices when only "special commits" (releases) need to be published.
 - Another one is the difficulties of building stats on releases downloads. GitHub does it but I don't see this feature being available for appveyor.

Please correct me if I am wrong and misinterpreted these appveyor aspects.

**Comment by chcg** [comment]
ok.

Sorry. I just meant testing the package.cmd scripts also via appveyor, not using appveyor build artifacts as official way of distribution. 

It is possible from the appveyor build to deploy the build result to github releases. On usecase is that it is automatically done on building a tag.

See:

```
+deploy:
+    provider: GitHub
+    auth_token:
+        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
+    artifact: releases
+    draft: false
+    prerelease: false
+    force_update: true
+    on:
+        appveyor_repo_tag: true
+        PlatformToolset: VS17
+        configuration: Release
```

, with the "on:" part the conditions could be controlled. It is also possible to do the deployment just manually.

**Comment by oleg-shilo** [comment]
Then we are on the same page. :)

I am actually done with the cs-script.x64.npp active development. All issues are solved. 
It just need a bit of testing and updating the packaging solution (that _package.cmd_). When it is released then the same approach can be implemented for scripts.npp as well.

BTW the binaries are all now assembled as a part of the build and eventually _package.cmd_ might not be even needed.

If you want to have an early look you can grab the both (x86/x64) packages form the dropbox file: https://www.dropbox.com/s/ifz1y2wuss5aslx/deployment.7z?dl=0

**Pull request merged**
